name: 'Form Data Http POST Action'
description: 'This action used to post form-data and/or upload file from repository'
branding:
  icon: 'upload'  
  color: 'blue'
inputs:
  url:
    description: 'The Endpoint of post request'
    required: true
  headers:
    description: 'The Headers of post request'
    required: false
  data:
    description: 'Form data'
    required: false
  name:
    description: 'File name'
    required: false
  file:
    description: 'File path'
    required: false
outputs:
  response:
    description: 'The response of POST request'
runs:
  using: 'node20'
  main: 'dist/index.js'
